set_property PACKAGE_PIN W7 [get_ports {segments[0]}]
set_property PACKAGE_PIN W6 [get_ports {segments[1]}]
set_property PACKAGE_PIN U8 [get_ports {segments[2]}]
set_property PACKAGE_PIN V8 [get_ports {segments[3]}]
set_property PACKAGE_PIN U5 [get_ports {segments[4]}]
set_property PACKAGE_PIN V5 [get_ports {segments[5]}]
set_property PACKAGE_PIN U7 [get_ports {segments[6]}]
set_property PACKAGE_PIN V7 [get_ports {segments[7]}]
set_property PACKAGE_PIN R2 [get_ports toggle]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports toggle]

set_property PACKAGE_PIN W5 [get_ports clock]
set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN W4 [get_ports {active[0]}]
set_property PACKAGE_PIN V4 [get_ports {active[1]}]
set_property PACKAGE_PIN U4 [get_ports {active[2]}]
set_property PACKAGE_PIN U2 [get_ports {active[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {active[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {active[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {active[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {active[0]}]

set_property PACKAGE_PIN V13 [get_ports testLED]
set_property IOSTANDARD LVCMOS33 [get_ports testLED]
